config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles
  validates :username, presence: true,
                       uniqueness: { case_sensitve: false },
                       length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true,
                    uniqueness: { case_sensitve: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
    
  end

  def index
    @articles = Article.all    
  end

  def new
    @article = Article.new 
  end

  def edit
   
  end

  def create 
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end  

  def update
     if @article.update(article_params)
      flash[:notice] = "Article updated successfully."
      redirect_to @article
    else 
       render 'edit'
    end 
  end

  def destroy
    
    @article.destroy
    redirect_to articles_path
  end

  private
  
  def set_article 
    @article = Article.find(params[:id])
  end

  def article_params
  params.require(:article).permit(:title, :description)
  end

end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'Your account information was successfully updated'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}. you have signed up successfully"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded-circle shadow mx-auto d-block')
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          By <%= article.user.username %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
          <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
          <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :title, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :description, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
        </div>
      </div>

      <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg"%>
      </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info " %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit articles</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<%= render 'article' %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          By <%= @article.user.username %>
        </div>
        <div class="card-body">
          <div class="card-text"><%= simple_format(@article.description) %></div>
          <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Sblend Digital", "https://sblend.co", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>AlphaBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="d-flex flex-column">
  <%= render 'layouts/navigation' %>
  <div id="page-content">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>

</html>

app/views/pages/about.html.erb
<h1>About Alpha Blog</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="container">
  <div class="jumbotron jumbotron-fluid mt-5 text-center text-white">
    <h1 class="display-4">Latest Articles</h1>
    <p class="lead">
      Welcome to our blog where we give you the latest gists and lifestyles. It's just like
      <br />
      getting your favorite coffee in the morning.
    </p>
    <%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :username, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :email, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :password, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
        </div>
      </div>

      <div class="form-group row justify-content-center">
        <%= f.submit(@user.new_record? ?  "Sign Up" : "Update account", class: "btn btn-outline-light btn-lg")%>
      </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info " %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile </h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container">
  <% @users.each do |user| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <%= link_to user.username, user %>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to gravatar_for(user, size:150), user %>
          </h5>
          <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
          <%= link_to "View profile", user, class: "btn btn-outline-success" %>
          <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
        </div>
        <div class="card-footer text-muted">
          <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4">
  <%= @user.username %>'s profile
</h1>

<%= gravatar_for @user, size: 200 %>

<h3 class="text-center mt-4">Articles
</h3>

<%= render 'articles/article' %>